name: Setup
on: push
jobs:
    up:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: make setup
            - run: make test
            - run: make lint