name: Setup
on: push
jobs:
    up:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup
              run: |
                make setup
                make test
                make lint
            - name: 'RunSnyk'
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - name: Node
              uses: actions/setup-node@v3
              with:
                cache: 'npm'